import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link' // Importing Link

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Workout Buddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="absolute left-1/2 top-1/2 w-52 lg:w-[900px] h-52 lg:h-[400px] bg-red-500 -translate-x-1/2 -translate-y-1/2 -z-10 blur-[150px] lg:blur-[325px]"></div>
        <div className="max-w-3xl mx-auto text-slate-100">
          <header className="p-6 border-b flex justify-between bg-red-400 rounded-bl-lg rounded br-lg mt-4">
            <Link className="text-2xl font-bold" href={'/'}>Workout Buddy</Link>
            <Link className="bg-slate-800 grid place-items-center py-2 px-4 rounded-full font-bold shadow-md" href={'/create'}>Add New</Link>
          </header>
          <main className="p-4 text-lg text-slate-800">{children}</main>
        </div>
      </body>
    </html>
  );
}
